### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by Molunerfinn** [PicGo/i18n#2]
1. 开发模式的 `NODE_ENV` 一般是 `development`，尤其是在 `Vue+Webpack` 的项目中比较普遍，可以做一下兼容或者直接使用 `development`
2. 无需在一开始就载入所有的语言文件，这样会占用内存。实际上修改语言之后，重启APP生效的操作很常见，因此一次只加载需要的语言文件是很重要的，能减少非常多的内存占用。

因此在初始化的时候，我们通常只需要指定一下当前的语言文件（或内容）即可。

```ts
import db from '@picgo/store'
import { I18n, FileSyncAdapter, ObjectAdapter } from '@picgo/i18n';
const lang = db.get('picgoSettings.language')

// 用fileSyncAdapter
const fileSyncAdapter = new FileSyncAdapter({
  localesBaseDir: path.resolve(__dirname, './locales'), // locales文件目录
  language: lang // <- 此时只需要加载对应的语言即可
});

const i18n = new I18n({
  adapter: fileSyncAdapter
});

const locales = require(`./locales/${lang}.json`) // 运行时加载对应的文件。此处简化逻辑，纯web环境可以用ajax获取。
// 用 objectAdapter
const objectAdapter = new ObjectAdapter(locales) // 适用于Web

const i18n = new I18n({
  adapter: objectAdapter
});
```

当然我觉得一开始都加载也是可以的（比如纯Web页面，无需刷新页面直接切换语言），不过可以增加一个选项来提供直接加载指定文件的模式，这样就更加灵活通用一点 🎉

**Comment by frank-mupt** [comment]
> 1. 开发模式的 `NODE_ENV` 一般是 `development`，尤其是在 `Vue+Webpack` 的项目中比较普遍，可以做一下兼容或者直接使用 `development`
> 2. 无需在一开始就载入所有的语言文件，这样会占用内存。实际上修改语言之后，重启APP生效的操作很常见，因此一次只加载需要的语言文件是很重要的，能减少非常多的内存占用。
> 
> 因此在初始化的时候，我们通常只需要指定一下当前的语言文件（或内容）即可。
> 
> ```ts
> import db from '@picgo/store'
> import { I18n, FileSyncAdapter, ObjectAdapter } from '@picgo/i18n';
> const lang = db.get('picgoSettings.language')
> 
> // 用fileSyncAdapter
> const fileSyncAdapter = new FileSyncAdapter({
>   localesBaseDir: path.resolve(__dirname, './locales'), // locales文件目录
>   language: lang // <- 此时只需要加载对应的语言即可
> });
> 
> const i18n = new I18n({
>   adapter: fileSyncAdapter
> });
> 
> const locales = require(`./locales/${lang}.json`) // 运行时加载对应的文件。此处简化逻辑，纯web环境可以用ajax获取。
> // 用 objectAdapter
> const objectAdapter = new ObjectAdapter(locales) // 适用于Web
> 
> const i18n = new I18n({
>   adapter: objectAdapter
> });
> ```
> 
> 当然我觉得一开始都加载也是可以的（比如纯Web页面，无需刷新页面直接切换语言），不过可以增加一个选项来提供直接加载指定文件的模式，这样就更加灵活通用一点 🎉
@Molunerfinn 
1. NODE_ENV 还是得使用普遍的表示模式，我去修改下
2. FIleSyncAdapter 并不会载入语言文件本身，不过会在初始化时保存 语言类型->文件名的一个映射，这个可以考虑做优化
![image](https://user-images.githubusercontent.com/18718461/80773006-2c68c480-8b8b-11ea-88ba-fa91e1e0516d.png)

**Comment by Molunerfinn** [comment]
OK，那其实就没啥问题，就算用Object模式的，只需要传入一种语言，然后在 `defaultLanguage` 那边指定一下就OK。
